# Assignment

<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sorted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted vocab after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your vocab and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

### Corpus

In [1]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [3]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [4]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [5]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [6]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [7]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### Your custom implementation

In [8]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

In [9]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

#### Custom FIT Function:

In [10]:
#Function to get idf values for every word in the vocabulary
def get_idf_values(corpus, vocab):
    dict_doc_term = {}
    idf_values = {}
    
    #Getting the length of the corpus or total number of documents present in the corpus
    num_doc_corpus = len(corpus)
    
    #Iterating over every word in the vocab
    for word in vocab:
    
        #Iterating over every document of the corpus
        for sent in corpus:
        
            #Checking if word is present in the current document
            if word in sent.split(" "):
                
                #Getting the latest count of documents containing the particular word (default count : 0)
                count = dict_doc_term.get(word,0)
                
                #Updating the count of word in the dictionary
                dict_doc_term[word] = count+1
                
                #Calculating the denominator of the idf formulae
                idf_denorm = dict_doc_term.get(word)
                
                #IDF value prior to log
                idf = (num_doc_corpus+1)/(idf_denorm+1)
                
                #Final IDF Value for the particular word
                final_idf = 1 + math.log(idf,2.7182818)
                
                #Updating the idf dictionary with the final idf value for the word
                idf_values[word]=final_idf
                
    return dict_doc_term,idf_values


#Function to create the Vocabulary for the given corpus
def fit(corpus):
    
    #Set of unique words present in the corpus
    unq_words = set()
    
    #Dictionary containing every word in vocab and its idf value
    idf_values = {}
    
    #Dictionary containing term and the count of unique documents where the term appears
    dict_doc_term = {}
    
    #Checking if the corpus is a list or not, proceed if yes
    if isinstance(corpus, (list,)):
        
        #Getting the length of corpus
        num_doc_corpus = len(corpus)
        
        #Iterating over every document in the corpus
        for sent in corpus:
            
            #Iterating over each word present in a document
            for word in sent.split(" "):
                
                #Discarding words if length is less than 2 (eg. a/an)
                if len(word)<2:
                    continue
                else:
                    
                    #Creating the set of unique words present in all documents of the corpus
                    unq_words.add(word)
        
        #Sorting the words in the set
        unq_words = sorted(list(unq_words))
        
        #Creating the vocabulary (with word and its index) for the corpus
        vocabulary = {j:i for i,j in enumerate(unq_words)}
        
        #Get the idf values of every word in the vocab
        dict_doc_term,idf_values = get_idf_values(corpus, unq_words)
        
        #Sort the idf values
        idf1 = sorted(idf_values)
        
        #Final sorted vocab with idf values
        sorted_idf = {key:idf_values[key] for key in idf1} 
        
        return vocabulary,sorted_idf,dict_doc_term
                
    else:
        print("Please provide correct input. Correct input is a list of strings")

#### Testing Custom TF-IDF Results with TfIdf Vectorizer result (After Fit Function)

In [11]:
#Fitting custom fit function on the corpus
custom_vocab,sorted_idf,dict_doc_term = fit(corpus)
print("Dictionary of Word and Count of documents it is present ::\n ", dict_doc_term)

Dictionary of Word and Count of documents it is present ::
  {'and': 1, 'document': 3, 'first': 2, 'is': 4, 'one': 1, 'second': 1, 'the': 4, 'third': 1, 'this': 4}


In [12]:
#Custom IDF Values for every word in vocab
sorted_idf

{'and': 1.9162907414672588,
 'document': 1.2231435536504107,
 'first': 1.5108256291140785,
 'is': 1.0,
 'one': 1.9162907414672588,
 'second': 1.9162907414672588,
 'the': 1.0,
 'third': 1.9162907414672588,
 'this': 1.0}

In [13]:
#IDF Values from vectorizer
print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [14]:
custom_vocab,sorted_idf,dict_doc_term = fit(corpus)
print('CUSTOM IMPLEMENTATION OF FIT : VOCAB ::\n ', list(custom_vocab.keys()))
print('='*100)
print('TFIDF Fit: \n',vectorizer.get_feature_names())

CUSTOM IMPLEMENTATION OF FIT : VOCAB ::
  ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
TFIDF Fit: 
 ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


#### Custom Transform Function:

In [24]:
#Defining the transform function
#Input parameters: corpus, vocab, idf values/word
def transform(corpus,custom_vocab,idf_values):
    
    rows = []
    columns = []
    values = []
    
    #Iterating over every document in corpus
    for idx,doc in enumerate(corpus):
        
        #Getting the index of the document in the corpus
        row_index = idx
        
        #Creating a dictionary to keep count of occurences of a word in a document
        col_checked = {}
        
        #Getting the count of words in the document
        tf_denorm = len(doc.split(" "))
        
        #Creating a dictionary containing words (present in the document) and their occurence
        tf_numerator_dict = dict(Counter(doc.split(" ")))
        
        #Checking the length of the each word in the dictionary and discarding ones that have length less than 2
        for word in doc.split(" "):
            
            if len(word)< 2:
                continue
        
            
            #Getting index of word in vocab (default index: -1 in case word is not present in vocab)
            col_idx = custom_vocab.get(word, -1)
            
            #Checking if the word is present in vocab or not
            if col_idx != -1:
                
                #Getting the count of occurences of the word in the document
                tf_num = tf_numerator_dict.get(word)
                
                #Getting the Term-Frequency values for the word
                tf = tf_num/tf_denorm
                
                #Getting IDF values for the word
                final_idf = idf_values.get(word)
                
                #Final Tf-IDf value for the word
                value = tf*final_idf
                
                #Checking the latest count of occurence of the word in the document
                count = col_checked.get(col_idx,0)
                
                #Updating the count
                col_checked[col_idx]= count+1
                
                #If the word is not processed then add the tfIdf value in the list
                if(col_checked[col_idx] ==1):
                    rows.append(row_index)
                    columns.append(col_idx)
                    values.append(value)
                
    #Creating the custom tf-idf sparse matrix 
    tdIdf_matrix = csr_matrix((values, (rows,columns)), shape=(len(corpus),len(custom_vocab)))
    
    #Normalizing the sparse tfidf matrix
    tfIdf_normalized = normalize(tdIdf_matrix, norm='l2')
    return tfIdf_normalized

#### Testing Custom TF-IDF Results with TfIdf Vectorizer result (After Transform Function)

In [25]:
#Fitting custom fit function on the corpus
custom_vocab,sorted_idf,dict_doc_term = fit(corpus)

#Custom transform function
custom_tfIdf = transform(corpus,custom_vocab,sorted_idf)

In [26]:
#Printing the result of transforming 1 document (Using custom tf-idf)
print("Custom TF-IDF values for Document index 0 :: \n", custom_tfIdf[0].toarray())

Custom TF-IDF values for Document index 0 :: 
 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [27]:
print("SKLearn TF-IDF values for Document index 0 :: \n", skl_output[0].toarray())

SKLearn TF-IDF values for Document index 0 :: 
 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [28]:
print("SKLearn IDF Values ::\n",vectorizer.idf_)

SKLearn IDF Values ::
 [1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [29]:
print("Custom IDF Values ::\n",sorted_idf)

Custom IDF Values ::
 {'and': 1.9162907414672588, 'document': 1.2231435536504107, 'first': 1.5108256291140785, 'is': 1.0, 'one': 1.9162907414672588, 'second': 1.9162907414672588, 'the': 1.0, 'third': 1.9162907414672588, 'this': 1.0}


In [31]:
print("Complete Sparse Matrix for Custom Tf-IDf Implementation :: \n\n",custom_tfIdf.toarray())

Complete Sparse Matrix for Custom Tf-IDf Implementation :: 

 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [32]:
print("Complete Sparse Matrix for SKLearn Tf-IDf Implementation :: \n\n",skl_output.toarray())

Complete Sparse Matrix for SKLearn Tf-IDf Implementation :: 

 [[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [33]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [34]:
corpus[:5]

['slow moving aimless movie distressed drifting young man',
 'not sure lost flat characters audience nearly half walked',
 'attempting artiness black white clever camera angles movie disappointed became even ridiculous acting poor plot lines almost non existent',
 'little music anything speak',
 'best scene movie gerardo trying find song keeps running head']

In [35]:
# Write your code here.
# Try not to hardcode any values.
# Make sure its well documented and readble with appropriate comments.

#Function to get idf values for top 50(max_feature) words in the vocabulary
def get_idf_values(corpus, vocab,max_features):
    
    dict_doc_term = {}
    idf_values = {}
    
    #Getting the length of the corpus or total number of documents present in the corpus
    num_doc_corpus = len(corpus)
    
    topWords = []
    idf_sorted = {}
    
    #Iterating over every word in the vocab
    for word in vocab:
    
        #Iterating over every document of the corpus
        for sent in corpus:
        
            #Checking if word is present in the current document
            if word in sent.split(" "):
                
                #Getting the latest count of documents containing the particular word (default count : 0)
                count = dict_doc_term.get(word,0)
                
                #Updating the count of word in the dictionary
                dict_doc_term[word] = count+1
                
                #Calculating the denominator of the idf formulae
                idf_denorm = dict_doc_term.get(word)
                
                #IDF value prior to log
                idf = (num_doc_corpus+1)/(idf_denorm+1)
                
                #Final IDF Value for the particular word
                final_idf = 1 + math.log(idf,2.7182818)
                
                #Updating the idf dictionary with the final idf value for the word
                idf_values[word]=final_idf
    
    #Sorting the idf values in descending order and selecting top 50 (max_features) words
    topWords = sorted(idf_values, key=lambda x: x[1], reverse=True)[:max_features]
    #topWords = sorted(idf_values, key=idf_values.get, reverse=True)[:max_features]
    
    #Getting the corresponding idf values for top 50 words
    for r in topWords:
        idf_sorted[r] = idf_values[r]
    
    return idf_sorted,topWords

#Function to create the Vocabulary of top 50 (max_features) words for the given corpus
def fit(corpus,max_features):
    
    #Set of unique words present in the corpus
    unq_words = set()
    
    #Dictionary containing every word in vocab and its idf value
    idf_values = {}
    
    #Checking if the corpus is a list or not, proceed if yes
    if isinstance(corpus, (list,)):
        
        #Getting the length of corpus
        num_doc_corpus = len(corpus)
        
        #Iterating over every document in the corpus
        for sent in corpus:
            
            #Iterating over each word present in a document
            for word in sent.split(" "):
                
                #Discarding words if length is less than 2 (eg. a/an)
                if len(word)<2:
                    continue
                else:
                    
                    #Creating the set of unique words present in all documents of the corpus
                    unq_words.add(word)
        
        #Sorting the words in the set
        unq_words = sorted(list(unq_words))
        
        #Get the idf values of top 50 word in the vocab
        idf_values,topWords = get_idf_values(corpus, unq_words,max_features)
        
        #Creating the vocabulary (with 50 words and their indices) for the corpus
        vocabulary = {j:i for i,j in enumerate(topWords)}
        
        return vocabulary,idf_values
                
    else:
        print("Please provide correct input. Correct input is a list of strings")

In [36]:
vocabulary,idf_sorted = fit(corpus,50)

#### Testing Custom TF-IDF Results with TfIdf Vectorizer result (After Fit Function with max_features functionality)

In [37]:
#Fitting custom fit function on the corpus
vocabulary,idf_sorted = fit(corpus,50)

In [38]:
print("Length of the vocabulary ::", len(vocabulary))

Length of the vocabulary :: 50


In [39]:
print("IDF values for top 50 words in corpus :: \n", idf_sorted)

IDF values for top 50 words in corpus :: 
 {'aye': 6.922918066582849, 'dysfunction': 6.922918066582849, 'eye': 6.517452954229668, 'eyes': 6.0066273251155895, 'hype': 6.922918066582849, 'hypocrisy': 6.922918066582849, 'lyrics': 6.922918066582849, 'mystifying': 6.922918066582849, 'oy': 6.922918066582849, 'pyromaniac': 6.922918066582849, 'ryan': 6.922918066582849, 'ryans': 6.922918066582849, 'sydney': 6.922918066582849, 'sympathetic': 6.922918066582849, 'syrupy': 6.922918066582849, 'system': 6.922918066582849, 'tying': 6.922918066582849, 'type': 6.517452954229668, 'typical': 6.922918066582849, 'exactly': 6.229770878766001, 'exaggerating': 6.922918066582849, 'example': 6.229770878766001, 'excellent': 4.977007897154833, 'excellently': 6.517452954229668, 'except': 6.922918066582849, 'exceptional': 6.517452954229668, 'exceptionally': 6.922918066582849, 'excerpts': 6.922918066582849, 'excessively': 6.922918066582849, 'exchange': 6.922918066582849, 'exciting': 6.922918066582849, 'excruciatingly

#### Custom Transform Function with max_features functionality:

In [40]:
#Defining the transform function
#Input parameters: corpus, vocab, idf values/word
def transform(corpus,custom_vocab,idf_sorted):
    
    rows = []
    columns = []
    values = []
    
    #Iterating over every document in corpus
    for idx,doc in enumerate(corpus):
        
        #Getting the index of the document in the corpus
        row_index = idx
        
        #Creating a dictionary to keep count of occurences of a word in a document
        col_checked = {}
        
        #Getting the count of words in the document
        tf_denorm = len(doc.split(" "))
        
        #Creating a dictionary containing words (present in the document) and their occurence
        tf_numerator_dict = dict(Counter(doc.split(" ")))
        
        #Checking the length of the each word in the dictionary and discarding ones that have length less than 2
        for word in doc.split(" "):
            if len(word)< 2:
                continue
        
            
            #Getting index of word in vocab (default index: -1 in case word is not present in vocab)
            col_idx = custom_vocab.get(word, -1)
            
            #Checking if the word is present in vocab or not
            if col_idx != -1:
                
                #Getting the count of occurences of the word in the document
                tf_num = tf_numerator_dict.get(word)
                
                #Getting the Term-Frequency values for the word
                tf = tf_num/tf_denorm
            
                #Getting IDF values for the word
                final_idf = idf_sorted.get(word)
                
                #Final Tf-IDf value for the word
                value = tf*final_idf
                
                #Checking the latest count of occurence of the word in the document
                count = col_checked.get(col_idx,0)
                
                #Updating the count
                col_checked[col_idx]= count+1
                
                #If the word is not processed then add the tfIdf value in the list
                if(col_checked[col_idx] ==1):
                    rows.append(row_index)
                    columns.append(col_idx)
                    values.append(value)
                
    #Creating the custom tf-idf sparse matrix
    tdIdf_matrix = csr_matrix((values, (rows,columns)), shape=(len(corpus),len(custom_vocab)))
    
    #Normalizing the sparse tfidf matrix
    tfIdf_normalized = normalize(tdIdf_matrix, norm='l2')
    return tdIdf_matrix

#### Testing Custom TF-IDF Results with TfIdf Vectorizer result (After Transform Function with max_features functionality)

#### Checking the result for 5 documents:

In [41]:
#Fitting custom fit function on the corpus
vocabulary,idf_sorted = fit(corpus[:5],50)

#Custom transform function
tdIdf_matrix = transform(corpus[:5],vocabulary,idf_sorted)

In [42]:
#Printing the result of transforming 1 document (Using custom tf-idf)
tdIdf_matrix[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.26232654, 0.        ,
        0.        , 0.        , 0.17568314, 0.26232654, 0.        ,
        0.        , 0.        , 0.        , 0.26232654, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.26232654, 0.26232654, 0.        , 0.26232654,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.26232654, 0.        ]])

#### Checking the result for all the documents:

In [43]:
#Fitting custom fit function on the corpus
vocabulary_fullCorp,idf_sorted = fit(corpus,50)

#Custom transform function
tdIdf_matrix_fullCorp = transform(corpus,vocabulary_fullCorp,idf_sorted)

In [44]:
print('Shape of tf-idf sparse matrix for entire corpus :: ',tdIdf_matrix_fullCorp.shape)

Shape of tf-idf sparse matrix for entire corpus ::  (746, 50)


In [46]:
print("Shape of tf-idf matrix for 1 document ::")
print(tdIdf_matrix_fullCorp[0].shape)

Shape of tf-idf matrix for 1 document ::
(1, 50)


In [47]:
print("Complete Sparse Matrix for Custom Tf-Idf Implementation with max_features functionality :: \n\n",tdIdf_matrix_fullCorp.toarray())

Complete Sparse Matrix for Custom Tf-Idf Implementation with max_features functionality :: 

 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
